security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: "%env(resolve:LDAP_BASE_DN)%"
                search_dn: "%env(resolve:LDAP_SEARCH_DN)%"
                search_password: "%env(resolve:LDAP_PASSWD)%"
                default_roles: ROLE_USER
                uid_key: sAMAccountName

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            form_login_ldap:
                login_path: login
                check_path: login
                default_target_path: userdata
                always_use_default_target_path: true
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'PASAIA\{username}'

            logout:
                path: /logout
                target: /

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin , roles: ROLE_ADMIN }
        - { path: ^/ , roles: ROLE_USER }
