version: "3.7"
services:
  db:
    container_name: zertegi_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - v_zertegi_db:/var/lib/postgresql/data:rw

  app:
    container_name: zertegi_app
    env_file: ./.env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - FOSJSDUMP=1
    user: "${USER_ID}:${GROUP_ID}"
    depends_on:
      - db
      - redis
    volumes:
      - ".:/usr/src/app"
      - "./docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro"
      - "./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro"
      - "./docker/uploads/:/usr/src/app/public/uploads"
    working_dir: /usr/src/app

  nginx:
    container_name: zertegi_nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./docker/ssl/:/etc/nginx/ssl/"
    volumes_from:
      - app
    working_dir: /usr/src/app

  redis:
    container_name: zertegi_redis
    image: redis:alpine
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:637"
    volumes:
      - v_zertegi_redis:/data


volumes:
  v_zertegi_db:
  v_zertegi_redis:
  v_zertegi_mysql:

networks:
  default:
    ipam:
      config:
        - subnet: 172.209.0.0/16
