version:  '3.7'
services:
  zertegi_mysql:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    restart: on-failure
    user: ${LOCAL_USER}

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - php

  adminer:
    image: adminer
    restart: on-failure
