home:
    path: /{_locale}
    controller: App\Controller\SecurityController::login
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'
