debug:
    path: /debug
    controller: App\Controller\DefaultController::debug
home:
    path: /{_locale}
    controller: App\Controller\SecurityController
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'
